version: '3.7'

services:
  consul_server:
    image: consul:latest
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8400:8400
      - 8500:8500
      - 8600:8600
    environment:
      NODE: consul_server
      PRIVATE_IP_ADDRESS: 33.10.0.2
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    command:
      "agent -server -dev -bind 33.10.0.2 -advertise 33.10.0.2 -node consul_server -ui -bootstrap -client 0.0.0.0"
    networks:
      consul_network:
        ipv4_address: 33.10.0.2

  mongodb:
    build:
      context: mongo
      dockerfile: Dockerfile
    image: mongo_consul
    container_name: mongodb-consul
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123
      MONGO_INITDB_DATABASE: tweets
      NODE: mongo
      MONGO_PORT: 27017
      PRIVATE_IP_ADDRESS: 33.10.0.3
    depends_on:
      - consul_server
    ports:
      - 27017:27017
    networks:
      consul_network:
        ipv4_address: 33.10.0.3

  tweeter:
    build:
      context: tweeter
      dockerfile: Dockerfile
    image: web_consul
    ports:
      - 5000:5000
    environment:
      NODE: web
      PRIMARY: 1
      PRIVATE_IP_ADDRESS: 33.10.0.10
    depends_on:
      - consul_server
      - mongodb
    volumes:
      - ./tweeter:/usr/src/app
    networks:
      consul_network:
        ipv4_address: 33.10.0.10

networks:
  consul_network:
    driver: bridge
    ipam:
      config:
        - subnet: 33.10.0.0/16